CREATE DATABASE PruebaTecnicaDB;
GO

USE PruebaTecnicaDB;
GO

CREATE TABLE Autores (
    AutorID INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(255) NOT NULL UNIQUE
);
GO

CREATE TABLE Libros (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Titulo NVARCHAR(255) NOT NULL,
    AutorID INT NOT NULL,
    FOREIGN KEY (AutorID) REFERENCES Autores(AutorID) ON DELETE NO ACTION
);
GO
